### ISSUE TITLE
[BUG] K9 Flase Flag KCAC

### ISSUE THREAD

**Issue by BurnhamR** [MTDOJRP/docs#100]
# In-Game Bug Report

## Description
Entering/Exiting K9 mode causes false flagging of KCAC

## Steps to Reproduce
1. Enter K9 Mode
2. Exit K9 Mode

## Expected Behavior
This behavior is expected and shouldn't be flagging KCAC

## Screenshots
![image](https://github.com/user-attachments/assets/721a2900-01ac-4a5a-88d8-bcadde576340)

## Additional Context
N/A

## Your Environment
- Windows 11

**Comment by Paneedah** [comment]
fixed in commit:
**KC-Menu:** [12c29be](https://github.com/MTDOJRP/KC-Menu/commit/12c29be70c889fbdfacb69d650c3d1301d89033f)
**KC-AntiCheet:** [1cfb4e1](https://github.com/MTDOJRP/KC-AntiCheet/commit/1cfb4e13fbdd5f566c69698e0747fbbb944e78d2)

**Comment by Paneedah** [comment]
moving to in-review for testing

**Comment by Paneedah** [comment]
Fix did not work

**Comment by BurnhamR** [comment]
Still Persistent.
Example:
https://discord.com/channels/1132847710282727565/1226928081466429491/1275901583007285463
